image:
  - Visual Studio 2017

platform:
  - Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '1.4.{version}'
  package_version: '1.4.{version}'
  assembly_version: '1.4.{version}'
  file_version: '1.4.{version}'
  informational_version: '1.4.{version}'

build_script:
  - pwsh: dotnet build --configuration Release
  - pwsh: dotnet test test/AD.IO.Tests --configuration Release