image: Visual Studio 2017

version: 1.5.{build}

branches:
  only:
    - master

environment:
  push: https://www.nuget.org/api/v2/package
  nuget:
    secure: lAOgXBlidUDKDMFlDJInIUO7K9vZc4FHLP715QyBp1gP9KFNQjntN70Jo6gi4+bA

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'

build_script:
  - pwsh: dotnet build -c Release

test_script:
  - pwsh: dotnet test test/AD.IO.Tests -c Release

deploy_script:
  - pwsh: dotnet nuget push src/AD.IO/bin/release/AD.IO.${env:appveyor_build_version}.nupkg -s ${env:push} -k ${env:nuget}