//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace AD.IO.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AD.IO.Standard.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Types xmlns=&quot;http://schemas.openxmlformats.org/package/2006/content-types&quot;&gt;
        ///  &lt;Default Extension=&quot;docx&quot; ContentType=&quot;application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml&quot;/&gt;
        ///  &lt;Default Extension=&quot;rels&quot; ContentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot;/&gt;
        ///  &lt;Default Extension=&quot;xlsx&quot; ContentType=&quot;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet&quot;/&gt;
        ///  &lt;Default Extension=&quot;xml&quot; ContentType [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _Content_Types_ {
            get {
                return ResourceManager.GetString("_Content_Types_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Properties xmlns=&quot;http://schemas.openxmlformats.org/officeDocument/2006/extended-properties&quot;
        ///            xmlns:vt=&quot;http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes&quot;&gt;
        ///  &lt;Template&gt;Normal.dotm&lt;/Template&gt;
        ///  &lt;TotalTime&gt;0&lt;/TotalTime&gt;
        ///  &lt;Pages&gt;1&lt;/Pages&gt;
        ///  &lt;Words&gt;0&lt;/Words&gt;
        ///  &lt;Characters&gt;0&lt;/Characters&gt;
        ///  &lt;Application&gt;Microsoft Office Word&lt;/Application&gt;
        ///  &lt;DocSecurity&gt;0&lt;/DocSecurity&gt;
        ///  &lt;Lines&gt;0&lt;/Lines&gt;
        ///  &lt;Paragraphs&gt;0&lt;/Paragraphs&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;cp:coreProperties xmlns:cp=&quot;http://schemas.openxmlformats.org/package/2006/metadata/core-properties&quot; 
        ///                   xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; 
        ///                   xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; 
        ///                   xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;dc:creator&gt;508 Programming Application&lt;/dc:creator&gt;
        ///  &lt;cp:lastModifiedBy&gt;508 Programming Application&lt;/cp:lastModifiedBy&gt;
        ///  &lt;cp:revision&gt;0&lt;/cp:r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string core {
            get {
                return ResourceManager.GetString("core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;w:document xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:body&gt;
        ///  &lt;/w:body&gt;
        ///&lt;/w:document&gt;.
        /// </summary>
        public static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///  &lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles&quot; Target=&quot;styles.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings&quot; Target=&quot;settings.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string document_xml_rels {
            get {
                return ResourceManager.GetString("document_xml_rels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:ftr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:jc w:val=&quot;right&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t&gt;U.S. International Trade Commission |&lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///    &lt;w:fldSimple w:instr=&quot; PAGE   \* MERGEFORMAT &quot;&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:t&gt;&lt;/w:t&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:fldSimple&gt;
        ///  &lt;/w:p&gt;
        ///&lt;/w:ftr&gt;.
        /// </summary>
        public static string footer1 {
            get {
                return ResourceManager.GetString("footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:ftr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:jc w:val=&quot;left&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:fldSimple w:instr=&quot; PAGE   \* MERGEFORMAT &quot;&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:t&gt;&lt;/w:t&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:fldSimple&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t&gt;| www.usitc.gov&lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///  &lt;/w:p&gt;
        ///&lt;/w:ftr&gt;.
        /// </summary>
        public static string footer2 {
            get {
                return ResourceManager.GetString("footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:footnotes xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:footnote w:type=&quot;separator&quot; w:id=&quot;-1&quot;&gt;
        ///    &lt;w:p&gt;
        ///      &lt;w:pPr&gt;
        ///        &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///      &lt;/w:pPr&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:separator/&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:p&gt;
        ///  &lt;/w:footnote&gt;
        ///  &lt;w:footnote w:type=&quot;continuationSeparator&quot; w:id=&quot;0&quot;&gt;
        ///    &lt;w:p&gt;
        ///      &lt;w:pPr&gt;
        ///        &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string footnotes {
            get {
                return ResourceManager.GetString("footnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///  
        ///&lt;/Relationships&gt;.
        /// </summary>
        public static string footnotes_xml_rels {
            get {
                return ResourceManager.GetString("footnotes_xml_rels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:hdr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:pStyle w:val=&quot;Header&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t xml:space=&quot;preserve&quot;&gt;Chapter &lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///    &lt;w:fldSimple w:instr=&quot; STYLEREF  &amp;quot;heading 1&amp;quot; \s \* &quot;&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:t/&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:fldSimple&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t xml:space=&quot;preserve&quot;&gt;: &lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///    &lt;w:fldSimple w:instr=&quot; STYLEREF   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string header1 {
            get {
                return ResourceManager.GetString("header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:hdr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:pStyle w:val=&quot;Header&quot;/&gt;
        ///      &lt;w:jc w:val=&quot;right&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t&gt;{0}&lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///  &lt;/w:p&gt;
        ///&lt;/w:hdr&gt;.
        /// </summary>
        public static string header2 {
            get {
                return ResourceManager.GetString("header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///  &lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument&quot; Target=&quot;word/document.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties&quot; Target=&quot;docProps/core.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rels {
            get {
                return ResourceManager.GetString("rels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:settings xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///            xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; 
        ///            xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; 
        ///            xmlns:m=&quot;http://schemas.openxmlformats.org/officeDocument/2006/math&quot; 
        ///            xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; 
        ///            xmlns:w10=&quot;urn:schemas-microsoft-com:office:word&quot; 
        ///            x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:styles xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///          xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; 
        ///          xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; 
        ///          xmlns:w14=&quot;http://schemas.microsoft.com/office/word/2010/wordml&quot; 
        ///          mc:Ignorable=&quot;w14&quot;&gt;
        ///  &lt;w:docDefaults&gt;
        ///    &lt;w:rPrDefault&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:asciiTheme=&quot;minor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string styles {
            get {
                return ResourceManager.GetString("styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;a:theme xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; name=&quot;Office Theme&quot;&gt;
        ///  &lt;a:themeElements&gt;
        ///    &lt;a:clrScheme name=&quot;Office&quot;&gt;
        ///      &lt;a:dk1&gt;
        ///        &lt;a:sysClr val=&quot;windowText&quot; lastClr=&quot;000000&quot;/&gt;
        ///      &lt;/a:dk1&gt;
        ///      &lt;a:lt1&gt;
        ///        &lt;a:sysClr val=&quot;window&quot; lastClr=&quot;FFFFFF&quot;/&gt;
        ///      &lt;/a:lt1&gt;
        ///      &lt;a:dk2&gt;
        ///        &lt;a:srgbClr val=&quot;1F497D&quot;/&gt;
        ///      &lt;/a:dk2&gt;
        ///      &lt;a:lt2&gt;
        ///        &lt;a:srgbClr val=&quot;EEECE1&quot;/&gt;
        ///      &lt;/a:lt2&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string theme1 {
            get {
                return ResourceManager.GetString("theme1", resourceCulture);
            }
        }
    }
}
